# Generated by Django 4.1.7 on 2023-03-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
