# Generated by Django 4.1.7 on 2023-03-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_carro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carro_alugueis', to='aluguel.carro', verbose_name='Carro'),
        ),
    ]
